#!/usr/bin/bash

set -euo pipefail

echo "************************ BUILD **************************"
export PATH="/usr/bin"
export CFLAGS=""
export LDFLAGS=""

meson setup --reconfigure build/release
exit 0
