#!/bin/bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: © 2024-present  Gene C <arch@sapience.com>
#
# installer script for cidrtools-ffi
# e.g. Call from PKGBUILD:  
#   ./do-install ${pkgdir}
#
set -euo pipefail

if (( $# < 1 )) ; then
    dest="./build/pkg"
else
    dest="$1"
fi
dest=$(realpath "$dest")

/usr/bin/meson install -C build/release --destdir "$dest" > /dev/null

exit 0

