#
# cidrtools-cffi/src/cidrtools/meson.build
#
py.install_sources(
  'cidr_blocks.py',
  '_core.py',
  'ct_add_cidr_to_cidrs.py',
  'ct_allocate_cidrs.py',
  'ct_cidr_contains_cidr.py',
  'ct_cidr_contains_ip.py',
  'ct_cidr_fix_host_bits.py',
  'ct_cidr_is_subnet.py',
  'ct_cidr_set_prefix.py',
  'ct_cidr_to_range.py',
  'ct_cidr_to_str.py',
  'ct_cidr_to_str_r.py',
  'ct_clean_cidr.py',
  'ct_clean_cidrs.py',
  'ct_compact.py',
  'ct_exclude_cidrs.py',
  'ct_format_host_bits.py',
  'ct_free_cidrs.py',
  'ct_get_host_bits.py',
  'ct_hostname_to_address.py',
  'ct_ip_address_increment.py',
  'ct_ip_address_range.py',
  'ct_ip_address_to_str.py',
  'ct_ip_address_to_str_r.py',
  'ct_ip_str_to_hostname.py',
  'ct_is_ipv4.py',
  'ct_is_ipv6.py',
  'ct_num_ips.py',
  'ct_range_to_cidrs.py',
  'ct_sort.py',
  'ct_split_by_family.py',
  'ct_str_to_cidr_block.py',
  'ct_str_to_cidr_parts.py',
  'ct_str_to_ip_address.py',
  'ct_subnets_split.py',
  'ct_version.py',
  '__init__.py',
  'tools.py',
  subdir: 'cidrtools'
)

